added skip option to allow skipping of uploading test artifacts
buildkite-plugins/test-collector-buildkite-plugin pull request #27
Opened 2022-12-13 22:24 UTC by CaseyPeters

2022-12-13 23:29 UTC, CaseyPeters commented on hooks/pre-exit
> +fi
followed same pattern used for `DEBUG`

2022-12-13 23:29 UTC, CaseyPeters commented on hooks/pre-exit
> +  fi
early exit!

2022-12-13 23:29 UTC, CaseyPeters commented on tests/pre-exit-success.bats
> +@test "Skips uploading files" {
These tests were pretty 🔥 so I thought it would be helpful to add one.

2022-12-14 12:29 UTC, toote requested changes
This is exactly the same as #14 but missing the change in `plugin.yml` (which is necessary). I also think that you can avoid the `SKIP` variable altogether and just do the `echo` and `exit` on the first `if` statement

2022-12-14 23:31 UTC, CaseyPeters commented
> Same as #14, I have a bee in my bonnet with adding this functionality instead of just using dynamic pipelines to not include the plugin if not wanted.
> 
> The explanation of the environment hook did provide me with more information and I kind of understand what you want/intend to do but I still think that there is a better way to do this without the need to add a plugin in a step that will not be used nor modify this plugin.
> 
> You can do something like the following (disclaimer, I have not tested this):
> 
> ```
> - name: "Unit Tests :junit:"
>   command: .buildkite/build-scripts/java-unit-test.sh
>   parallelism: 2
>   artifact_paths:
>     - 'jacoco/**/*'
>     - 'surefire-reports/**/*'
>     - 'logs/*'
>   plugins:
>     - docker-compose#v3.9.0:
>         run: app
>         config: docker-compose.buildkite.yml
>         pull-retries: 1
>         dependencies: false
> - name: "Test Analytics"
>   if: build.branch != "development"
>   command: buildkite-agent artifact download surefire-reports/**/*
>   plugins:
>     - test-collector#v1.0.0:
>         files: "surefire-reports/*.xml"
>         format: "junit"
>         api-token-env-name: "BUILDKITE_ANALYTICS_TOKEN_UNIT"
> ```
> 
> That said, I think that there is a necessary feature here that is not the ability to skip upload but to only do uploads on certain branches (or exclude some) that would actually be a lot more useful (and avoid the need for dynamic pipelines, an additional hook or step)

I completely agree that a dynamic pipeline would solve this problem. however, our pipeline file is on the larger side at this point, and rewriting this one repo's pipeline to be dynamic would be much larger in scope than adding this skip variable.  Also, I think that would raise a lot of concerns around the introduced complexity due to the difficult nature of testing all the potential pipeline scenarios for our company.

I do like the idea of a filter based on branch name let me think more about that avenue rather than the simple "skip" option. This would act more of a allow/deny list scenario.

Would you think that a `branches` parameter would behave similarly to [branch configuration](https://buildkite.com/docs/pipelines/branch-configuration#branch-pattern-examples)

2022-12-15 05:32 UTC, toote commented
> I do like the idea of a filter based on branch name let me think more about that avenue rather than the simple "skip" option. This would act more of a allow/deny list scenario.
> 

I started working on this on my own but got distracted by something else

> Would you think that a `branches` parameter would behave similarly to [branch configuration](https://buildkite.com/docs/pipelines/branch-configuration#branch-pattern-examples)

That would be awesome but incredibly complicated to implement in bash so I am thinking about something a lot simpler. Will open a PR shorty (hopefully)

2022-12-15 05:51 UTC, toote commented
@CaseyPeters I just created #28 with my idea :)

2022-12-15 20:21 UTC, CaseyPeters commented
Closing this PR because #28 achieves what I need in a more complete way.

2022-12-15 20:21 UTC, closed without merging